### ISSUE TITLE
Troubles understanding what is Eventlog, and why it is necessary

### ISSUE THREAD

**Issue by Spl3en** [icon-project/icon-project.github.io#16]
Hello, 

I'm having troubles understanding what is the `@eventlog` decorator, and why it is necessary in the IRC2 Token standard. Also, their parameter `indexed` is also a mystery for me.

If necessary, may you detail its purpose in the documentation please ?
Thank you very much.

**Comment by sink772** [comment]
Actually we have a Korean version document of what the `evenlog` is.
https://github.com/icon-project/icon-service/blob/develop/docs/event-log-and-bloom-filter.md

By using `eventlog`, 3rd-party applications like tracker are able to know the actual token transfers within SCORE.

**Comment by Spl3en** [comment]
Thank you very much @sink772 for pointing me to the icon-service documentation. 
I can't understand Korean but I found [another document](https://github.com/icon-project/icon-service/blob/develop/docs/dapp_guide.md) in English that helped me understanding that `eventlog` will include logs in its TxResult as 'eventlogs'. Awesome!

Have a nice weekend 🌞
